export type Role = "mafia" | "doctor" | "detective" | "bodyguard" | "trickster" | "citizen" | "spectator";
export type Phase = "lobby" | "reveal" | "night" | "dawn" | "day" | "vote" | "defense" | "verdict" | "result" | "gameover";

export type PlayerState = {
  id: string;
  n: string;
  alive: boolean;
  connected: boolean;
  ready: boolean;
  votes: number;
  mafia: boolean;
  role: Role | null;
  bot: boolean;
  bot_profile?: string | null;
  bot_persona?: string | null;
  score: number;
  voice: boolean;
};

export type ChatMessage = { id: string; from: string; from_id?: string; text: string; at: number };
export type CaseProfile = { id: string; code: string; title: string; location: string; victim: string; briefing: string };
export type ReactionState = { id: string; from: string; emoji: string; at: number };
export type ReadStance = "trust" | "hold" | "suspect";
export type InterrogationQuestion = { id: string; from: string; from_id: string; speaker_id: string; text: string; round: number; at: number };
export type SealedClaim = { id: string; speaker_id: string; speaker: string; text: string; round: number; at: number };
export type CaseMoment = { id: string; kind: string; text: string; actor: string | null; target: string | null; round: number };
export type BallotEntry = { voter_id: string; voter: string; target_id: string; target: string };
export type CaseClue = { id: string; code: string; round: number; title: string; detail: string; outcome: string; suspect_ids: string[]; suspects: string[] };
export type PrivateLead = { id: string; title: string; detail: string; suspect_id: string; revealed: boolean };
export type PublicLead = { id: string; owner_id: string; owner: string; title: string; detail: string; round: number; suspect_id: string };
export type RoundEvent = { id: string; title: string; tag: string; copy: string; sealed_pressure: boolean };
export type CaseAward = { id: string; player_id: string; player: string; title: string; copy: string };
export type AnonymousTip = { id: string; text: string; round: number; at: number };
export type MemorySeal = { id: string; owner_id: string; owner: string; text: string; round: number; sealed_at: number };
export type SceneFragment = { id: string; time: string; title: string; detail: string };
export type SceneResult = { round: number; score: number; total: number; correct_pairs: number; submitted_at: number };
export type OathState = { id: string; owner_id: string; owner: string; target_id: string; target: string; text: string; round: number; kept: boolean | null };
export type GhostEcho = { id: string; owner_id: string; owner: string; text: string; round: number; at: number };
export type DirectorBeat = { id: string; round: number; title: string; copy: string; tone: string; at: number };

export type GameState = {
  t: "state";
  room: string;
  case_profile: CaseProfile;
  round_event: RoundEvent | null;
  tips: AnonymousTip[];
  pressure_counts: Record<string, number>;
  pressure_progress: { completed: number; total: number; sealed: boolean };
  awards: CaseAward[];
  phase: Phase;
  round: number;
  mode?: "solo" | "party";
  lobby_mode?: "solo" | "party";
  deadline: number;
  winner: "mafia" | "citizen" | "trickster" | null;
  pace: "quick" | "classic";
  host: string | null;
  min_players: number;
  max_players: number;
  players: PlayerState[];
  me: {
    id: string;
    role: Role;
    alive: boolean;
    action_target: string | null;
    vote_target: string | null;
    judgement?: boolean | null;
    intel: string[];
    mission: string;
    mission_completed: boolean;
    can_tip: boolean;
    reads: Record<string, ReadStance>;
    can_leave_will: boolean;
    private_lead: PrivateLead | null;
    ghost_prediction: string | null;
    ghost_correct: boolean | null;
    pressure_target: string | null;
    memory_prompt: string;
    memory_seal: MemorySeal | null;
    can_seal_memory: boolean;
    scene_fragments: SceneFragment[];
    scene_result: SceneResult | null;
    can_reconstruct: boolean;
    oath_target: string | null;
    oath_text: string;
    can_oath: boolean;
    can_ghost_message: boolean;
    ghost_message: string | null;
  };
  story: string[];
  case_log: string[];
  clues: CaseClue[];
  public_leads: PublicLead[];
  memory_reveals: MemorySeal[];
  scene_progress: { completed: number; total: number };
  oaths: OathState[];
  ghost_echoes: GhostEcho[];
  director_beats: DirectorBeat[];
  accused_id: string | null;
  judgement_counts: { execute: number; spare: number };
  decision_progress: { completed: number; total: number };
  ballot_feed: BallotEntry[];
  guide: string;
  chat: ChatMessage[];
  reactions: ReactionState[];
  speaker_id: string | null;
  speaker_deadline: number;
  interrogation_order: string[];
  questions: InterrogationQuestion[];
  claims: SealedClaim[];
  read_summary: Record<string, Record<ReadStance, number>>;
  moments: CaseMoment[];
};

export type WelcomeMsg = {
  t: "welcome";
  id: string;
  nick: string;
  room: string;
  player_key: string;
  signed_in: boolean;
  resumed: boolean;
};
